/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowAuthentification (void);
GtkWidget* create_admin_addEts_achref (void);
GtkWidget* create_Modifier_ETS_achref (void);
GtkWidget* create_DeleteEts_achref (void);
GtkWidget* create_espaceAdmin (void);
GtkWidget* create_Firas_Ajout (void);
GtkWidget* create_Firas_Suppression (void);
GtkWidget* create_Firas_Modifier (void);
GtkWidget* create_Succeed_Supp (void);
GtkWidget* create_menu_Firas (void);
GtkWidget* create_Interface_De_la_page_Dacceuil (void);
GtkWidget* create_Interface_D_ajout_de_RDV (void);
GtkWidget* create_Interface_De_la_Confirmation_De_RDV (void);
GtkWidget* create_Interface_De_La_Modification (void);
GtkWidget* create_Interface_De_La_Confirmation_De_La_Modification_De_RDV (void);
GtkWidget* create_Interface_De_Suppression_De_RDV (void);
GtkWidget* create_Interface_De_Confirmation_De_Suppression_Des_RDV (void);
GtkWidget* create_Interface_D_affichage_RDV (void);
GtkWidget* create_MDF_Avec_SUCESS (void);
GtkWidget* create_Interface_De_Deconnection_ (void);
GtkWidget* create_Interface_Help (void);
GtkWidget* create_affichage (void);
GtkWidget* create_ajout (void);
GtkWidget* create_confirmation_bekri (void);
GtkWidget* create_modifier (void);
GtkWidget* create_suppression (void);
GtkWidget* create_stat1 (void);
GtkWidget* create_stat2 (void);
GtkWidget* create_yasmine_home_window (void);
GtkWidget* create_yasmine_ajout_window (void);
GtkWidget* create_yasmine_update_window (void);
GtkWidget* create_yasmine_delete_window (void);
GtkWidget* create_yasmine_sang_plusRare_window (void);
GtkWidget* create_yasmine_quantite_type_window (void);
GtkWidget* create_Espace_Infirmier (void);
